# Generated by Django 4.0.6 on 2022-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('num_habitaciones', models.IntegerField()),
                ('num_baños', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
                'ordering': ['nombre'],
            },
        ),
    ]
