# Generated by Django 4.0.6 on 2022-09-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('a_paterno', models.CharField(max_length=200)),
                ('a_materno', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('num_contacto', models.IntegerField()),
                ('tipo_de_usuario', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['rut_usuario'],
            },
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamentos', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
