# Generated by Django 3.2.3 on 2022-10-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
